package AdactinApplication;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class AdactinHotelApplication {

	public static void main(String[] args) throws Exception {
		System.setProperty("webdriver.chrome.driver", "C://chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.get("https://adactinhotelapp.com/");
		driver.manage().window().maximize();
		driver.findElement(By.id("username")).sendKeys("RickRonald12");
		Thread.sleep(500);
		driver.findElement(By.id("password")).sendKeys("PU4PQ1");
		Thread.sleep(500);
		driver.findElement(By.id("login")).click();
		Thread.sleep(500);
		WebElement Dropdown = driver.findElement(By.name("location"));
		Thread.sleep(500);
		Select select = new Select(Dropdown);
		Thread.sleep(500);
		select.selectByIndex(1);
		Thread.sleep(500);
		WebElement DP = driver.findElement(By.name("hotels"));

		Thread.sleep(500);
		Select sl = new Select(DP);
		Thread.sleep(500);
		sl.selectByIndex(1);
		Thread.sleep(500);
		WebElement hotel = driver.findElement(By.name("room_type"));
		Thread.sleep(500);
		Select sp = new Select(hotel);
		sp.selectByIndex(1);
		Thread.sleep(500);
		WebElement RoomNo = driver.findElement(By.xpath("//*[@id=\"room_nos\"]"));
		// Thread.sleep(3000);
		Select Rooms = new Select(RoomNo);
		// Thread.sleep(3000);
		Rooms.selectByIndex(1);
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).clear();
		final String sdate = "25/01/2023";
		Thread.sleep(500);
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date = df.parse(sdate); // conversion from StringThread.sleep(3000);
		java.util.Calendar S1 = GregorianCalendar.getInstance();
		Thread.sleep(500);
		S1.setTime(date);
		S1.add(GregorianCalendar.DAY_OF_WEEK, 7);
		Thread.sleep(500);
		System.out.println(df.format(S1.getTime()));
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).sendKeys(df.format(S1.getTime()));
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).clear();
		Thread.sleep(500);
		final String sdate1 = "25/01/2023";
		SimpleDateFormat df1 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date1 = df1.parse(sdate1); // conversion from String
		Thread.sleep(500);
		java.util.Calendar S11 = GregorianCalendar.getInstance();
		S11.setTime(date1);
		S11.add(GregorianCalendar.DAY_OF_WEEK, 5);
		System.out.println(df1.format(S11.getTime()));
		driver.findElement(By.id("datepick_out")).sendKeys(df1.format(S11.getTime()));
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).clear();
		final String sdate11 = "25/01/2023";
		Thread.sleep(500);
		SimpleDateFormat df12 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date12 = df1.parse(sdate11); // conversion from StringThread.sleep(3000);
		java.util.Calendar S112 = GregorianCalendar.getInstance();
		Thread.sleep(500);
		S112.setTime(date1);
		S112.add(GregorianCalendar.DAY_OF_WEEK, -5);
		Thread.sleep(500);
		System.out.println(df1.format(S112.getTime()));
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).sendKeys(df1.format(S112.getTime()));
		Thread.sleep(500);
		// driver.findElement(By.id("datepick_in")).clear();
		Thread.sleep(500);
		final String sdate13 = "25/01/2023";
		SimpleDateFormat df13 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date11 = df13.parse(sdate13); // conversion from String
		Thread.sleep(500);
		java.util.Calendar S113 = GregorianCalendar.getInstance();
		S11.setTime(date11);
		S11.add(GregorianCalendar.DAY_OF_WEEK, -3);
		System.out.println(df1.format(S113.getTime()));
		driver.findElement(By.id("datepick_out")).sendKeys(df1.format(S11.getTime()));
		Thread.sleep(500);
		WebElement DPs = driver.findElement(By.id("adult_room"));
		Select sl1 = new Select(DPs);
		sl1.selectByIndex(0);
		Thread.sleep(500);
		WebElement DPss = driver.findElement(By.id("child_room"));
		Select sl12 = new Select(DPss);
		sl1.selectByIndex(1);
		Thread.sleep(500);
		driver.findElement(By.id("Submit")).click();
		driver.navigate().back();
		final String sdate113 = "25/01/2023";
		Thread.sleep(500);
		SimpleDateFormat df113 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date112 = df113.parse(sdate113); // conversion from StringThread.sleep(3000);
		java.util.Calendar S114 = GregorianCalendar.getInstance();
		Thread.sleep(500);
		S112.setTime(date1);
		S112.add(GregorianCalendar.DAY_OF_WEEK, 0);
		Thread.sleep(500);
		System.out.println(df1.format(S112.getTime()));
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).sendKeys(df1.format(S112.getTime()));
		Thread.sleep(500);
		// driver.findElement(By.id("datepick_in")).clear();
		Thread.sleep(500);
		final String sdate14 = "25/01/2023";
		SimpleDateFormat df14 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date14 = df14.parse(sdate14); // conversion from String
		Thread.sleep(500);
		java.util.Calendar S115 = GregorianCalendar.getInstance();
		S11.setTime(date14);
		S11.add(GregorianCalendar.DAY_OF_WEEK, 1);
		System.out.println(df1.format(S11.getTime()));
		driver.findElement(By.id("datepick_out")).sendKeys(df1.format(S11.getTime()));
		Thread.sleep(500);
		final String sdate115 = "25/01/2023";
		Thread.sleep(500);
		SimpleDateFormat df115 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date115 = df115.parse(sdate11); // conversion from StringThread.sleep(3000);
		java.util.Calendar S1151 = GregorianCalendar.getInstance();
		Thread.sleep(500);
		S112.setTime(date1);
		S112.add(GregorianCalendar.DAY_OF_WEEK, 0);
		Thread.sleep(500);
		System.out.println(df1.format(S112.getTime()));
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).sendKeys(df1.format(S112.getTime()));
		Thread.sleep(500);
		// driver.findElement(By.id("datepick_in")).clear();
		Thread.sleep(500);
		final String sdate15 = "25/01/2023";
		SimpleDateFormat df15 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date15 = df15.parse(sdate15); // conversion from String
		Thread.sleep(500);
		java.util.Calendar S1165 = GregorianCalendar.getInstance();
		S11.setTime(date15);
		S11.add(GregorianCalendar.DAY_OF_WEEK, 1);
		System.out.println(df1.format(S11.getTime()));
		driver.findElement(By.id("datepick_out")).sendKeys(df1.format(S11.getTime()));
		Thread.sleep(500);
		WebElement RoomNo3 = driver.findElement(By.xpath("//*[@id=\"room_nos\"]"));
		// Thread.sleep(3000);
		Select Rooms3 = new Select(RoomNo3);
		// Thread.sleep(3000);
		Rooms3.selectByIndex(3);
		Thread.sleep(500);
		// System.out.println("----------------------------------------------------------------------------------");
		WebElement hotel113 = driver.findElement(By.name("room_type"));
		Thread.sleep(500);
		Select sp012 = new Select(hotel113);
		sp012.selectByIndex(3);
		driver.getTitle();
		Thread.sleep(500);
		final String sdate116 = "25/01/2023";
		Thread.sleep(500);
		SimpleDateFormat df116 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date116 = df116.parse(sdate116); // conversion from StringThread.sleep(3000);
		java.util.Calendar S1156 = GregorianCalendar.getInstance();
		Thread.sleep(500);
		S112.setTime(date1);
		S112.add(GregorianCalendar.DAY_OF_WEEK, 0);
		Thread.sleep(500);
		System.out.println(df1.format(S112.getTime()));
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).sendKeys(df1.format(S112.getTime()));
		Thread.sleep(500);
		// driver.findElement(By.id("datepick_in")).clear();
		Thread.sleep(500);
		final String sdate17 = "25/01/2023";
		SimpleDateFormat df17 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date17 = df17.parse(sdate17); // conversion from String
		Thread.sleep(500);
		java.util.Calendar S1167 = GregorianCalendar.getInstance();
		S11.setTime(date14);
		S11.add(GregorianCalendar.DAY_OF_WEEK, 1);
		System.out.println(df1.format(S11.getTime()));
		driver.findElement(By.id("datepick_out")).sendKeys(df1.format(S11.getTime()));
		WebElement RoomNo2 = driver.findElement(By.xpath("//*[@id=\"room_nos\"]"));
		// Thread.sleep(3000);
		Select Rooms2 = new Select(RoomNo2);
		// Thread.sleep(1000);
		Rooms2.selectByIndex(2);
		Thread.sleep(500);
		final String sdate117 = "24/01/2023";
		Thread.sleep(500);
		SimpleDateFormat df117 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(500);
		Date date117 = df117.parse(sdate117); // conversion from StringThread.sleep(3000);
		java.util.Calendar S117 = GregorianCalendar.getInstance();
		Thread.sleep(500);
		S112.setTime(date1);
		S112.add(GregorianCalendar.DAY_OF_WEEK, 0);
		Thread.sleep(500);
		System.out.println(df1.format(S112.getTime()));
		Thread.sleep(500);
		driver.findElement(By.id("datepick_in")).sendKeys(df1.format(S112.getTime()));
		Thread.sleep(500);
		// driver.findElement(By.id("datepick_in")).clear();
		Thread.sleep(500);
		final String sdate18 = "25/01/2023";
		SimpleDateFormat df18 = new SimpleDateFormat("dd/MM/yyyy");
		Thread.sleep(1000);
		Date date18 = df18.parse(sdate18); // conversion from String
		Thread.sleep(500);
		java.util.Calendar S118 = GregorianCalendar.getInstance();
		S11.setTime(date18);
		S11.add(GregorianCalendar.DAY_OF_WEEK, 1);
		System.out.println(df1.format(S11.getTime()));
		driver.findElement(By.id("datepick_out")).sendKeys(df1.format(S11.getTime()));
		Thread.sleep(500);
		// driver.findElement(By.xpath("/html/body/table[2]/tbody/tr[1]/td[2]/a[4]")).click();
		driver.findElement(By.id("Submit")).click();

	}
}
